name: Build
permissions:
  contents: write
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0" # will fetch the entire history

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.16.5

      - name: Install dependencies
        run: flutter pub get

      - name: Check if release is needed
        id: check_release
        run: |
          RELEASE_OUTPUT=$(dart run release_tools should_release)
          echo "should_release=$RELEASE_OUTPUT" >> $GITHUB_OUTPUT

      - name: Prepare release
        if: steps.check_release.outputs.should_release == 'yes'
        run: dart run release_tools prepare_release

      - name: Extract version from pubspec.yaml
        id: extract_version
        run: echo "VERSION=$(grep "version:" pubspec.yaml | grep -oP '(?<=version:\s)[^+]+')" >> $GITHUB_ENV

      - name: Release version
        if: steps.check_release.outputs.should_release == 'yes'
        uses: EndBug/add-and-commit@v9
        with:
          message: "ci: Release version ${{ env.VERSION }}"
          tag: "v${{ env.VERSION }}"

      - name: Build project
        if: steps.check_release.outputs.should_release == 'yes'
        run: flutter build web

      - name: Log in to Docker Hub
        if: steps.check_release.outputs.should_release == 'yes'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and push Docker image
        if: steps.check_release.outputs.should_release == 'yes'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bflow-client:${{ env.VERSION }}
