name: Deploy Docker Image

on:
  push:
    branches: [ "release" ]

jobs:
      
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.16.5
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build project
      run: flutter build web
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}
        
    - name: Extract version from pubspec.yaml
      id: extract_version
      run: echo "VERSION=$(grep "version:" pubspec.yaml | grep -oP '(?<=version:\s)[^+]+')" >> $GITHUB_ENV
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/bflow-client:${{ env.VERSION }}
      
