name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sdtorresl/bflow-client:$(grep version: pubspec.yaml | grep -oP '(?<=version:\s)[^+]+')
