name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
      
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.16.5
    - run: flutter pub get
    - run: flutter build web
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sdtorresl/bflow-client:$(grep "version:" pubspec.yaml | grep -oP '(?<=version:\s)[^+]+')
