name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
      
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.16.5
    - name: Install dependencies
      run: flutter pub get
    - name: Build project
      run: flutter build web
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/bflow-client:$(grep "version:" pubspec.yaml | grep -oP '(?<=version:\s)[^+]+')
      
